# ============================================
# Переменные уровня pipeline (общие для всех job)
# ============================================
variables:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: ppm_database
  POSTGRES_USER: login_ppm
  POSTGRES_PASSWORD: $PG_SECRET

  VAULT_ADDR: http://vault:8200
  VAULT_TOKEN: root
  VAULT_DATABASE_ROLE_NAME: postgres-dynamic
  VAULT_ADMIN_PASSWORD: admin

  DB_CREDS_MODE: static
  
stages:
  - Build_image
  - Test_lint_unit
  - Build backend_image
  - Test_integration_e2e

# ============================================
# Stage 0: Build Images 
# ============================================
build_images_job:
  stage: Build_image
  rules:
  - changes:
      - docker_images/*
  tags: [docker]
  image: docker:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD localhost:5050
  script:
    - docker build -t localhost:5050/root/opscontrol/lint-image:latest -f docker_images/Dockerfile-lint .
    - docker build -t localhost:5050/root/opscontrol/unit-image:latest -f docker_images/Dockerfile-unit .
    - docker build -t localhost:5050/root/opscontrol/int-image:latest -f docker_images/Dockerfile-int .
    - docker push localhost:5050/root/opscontrol/lint-image:latest
    - docker push localhost:5050/root/opscontrol/unit-image:latest
    - docker push localhost:5050/root/opscontrol/int-image:latest

# ============================================
# Stage 1: Lint & Unit Tests
# ============================================
lint_job:
  stage: Test_lint_unit
  tags: [docker]
  image: localhost:5050/root/opscontrol/lint-image:latest
  timeout: 2 minutes
  script:
    - ruff check backend/
    - black --check backend/

unit_tests_job:
  stage: Test_lint_unit
  tags:
    - docker
  image: localhost:5050/root/opscontrol/unit-image:latest
  timeout: 2 minutes
  script:
    - export COVERAGE_FILE=.coverage.unit
    - PYTHONPATH=backend pytest backend/scripts/tests/unit-testings/ --cov=backend --cov-report=term --cov-report= --cov-config=.coveragerc

  artifacts:
    paths:
      - .coverage.unit

# ============================================
# Stage 2: Build Image Backend 
# ============================================
build_images_project_job:
  stage: Build_image_backend
  tags: [docker]
  image: docker:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD localhost:5050
  script:
    - docker build -t localhost:5050/root/opscontrol/backend-image:$CI_COMMIT_SHA -f Dockerfile .
    - docker push localhost:5050/root/opscontrol/backend-image:$CI_COMMIT_SHA

# ============================================
# Stage 3: integration-e2e Tests
# ============================================
integration-job:
  stage: Test_integration_e2e
  tags: [docker]
  image: localhost:5050/root/opscontrol/int-image:latest
  timeout: 5 minutes

  services:
    - name: postgres:15
      alias: postgres
    - name: hashicorp/vault:1.15
      alias: vault
      command: ["vault","server","-dev","-dev-root-token-id=root","-dev-listen-address=0.0.0.0:8200"]
    - name: localhost:5050/root/opscontrol/backend:$CI_COMMIT_SHA
      alias: backend 

  script:
    # Ждём Postgres
    - echo "Ждём postgres..."
    - until pg_isready -h postgres -p 5432; do sleep 1; done

    - echo "Применяем init.sql..."
    - PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -f backend/scripts/init.sql

    # Ждём Vault
    - echo "Ждём vault..."
    - until curl -s -o /dev/null -w "%{http_code}" http://vault:8200/v1/sys/health | grep -q "200"; do sleep 1; done

    # Резолвим IP postgres для Vault
    - export POSTGRES_IP=$(getent hosts postgres | awk '{print $1}')
    - echo "Postgres IP = $POSTGRES_IP"

    # Запуск скрипта Vault
    - sh backend/scripts/vault-init-dev.sh

    # Устанавливаем VAULT_ROLE_ID и VAULT_SECRET_ID сгенерированные скриптом
    - export $(cat /tmp/vault_creds.env | xargs)

    # Интеграционные тесты
    - export COVERAGE_FILE=.coverage.integration
    - PYTHONPATH=backend pytest backend/scripts/tests/integ-testings/ --cov=backend --cov-report=term --cov-report= --cov-config=.coveragerc

    # Ждём бэкенд
    - until curl -s http://backend:8000/health; do sleep 1; done

    # E2e (через HTTP к бэкенду)
    #- pytest e2e-testings/ -m e2e

  artifacts:
    paths:
      - .coverage.integration

# -------------------------
# MERGE COVERAGE
# -------------------------
coverage_merge:
  stage: Test_integration_e2e
  image: localhost:5050/root/opscontrol/int-image:latest
  tags: [docker]

  needs:
    - job: unit_tests_job
      artifacts: true
    - job: integration-job
      artifacts: true

  script:
    - coverage combine
    - coverage xml -o coverage.xml
    - coverage report

  coverage: '/TOTAL.*\s+(\d+%)$/'

  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml