stages:
  - test
  #- build
  #- deploy

test-job:
  stage: test
  tags:
    - docker
  image: localhost:5050/root/opscontrol/ci-image:latest

  services:
    - name: postgres:15
      alias: postgres
    - name: hashicorp/vault:1.15
      alias: vault
      command: ["vault", "server", "-dev", "-dev-root-token-id=root"]

  variables:
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_DB: ppm_database
    POSTGRES_USER: login_ppm
    POSTGRES_PASSWORD: $PG_SECRET
    VAULT_ADDR: http://vault:8200
    VAULT_TOKEN: root
    
  script:
      # Ждём Postgres
    - echo "Ждём postgres..."
    - until pg_isready -h postgres -p 5432; do sleep 1; done

    # Проверка доступности БД
    - python backend/scripts/connect-pg-test.py

    # Инициализация БД (правильно)
    - echo "Применяем init.sql..."
    - PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -f backend/scripts/init.sql

    # Ждём Vault (debug)
    - echo "=== VAULT DEBUG ==="
    - which curl || echo "curl NOT FOUND"
    - getent hosts vault || echo "vault DNS FAIL"
    - curl -v http://vault:8200/v1/sys/health || true
    - echo "=== END DEBUG ==="

    # Ждём Vault
    #- echo "Ждём vault..."
    #- until curl -s -o /dev/null -w "%{http_code}" http://vault:8200/v1/sys/health | grep -q "200"; do sleep 1; done

    # Запуск скрипта Vault
    - sh backend/scripts/vault-init.sh
