stages:
  - test

test-job:
  stage: test
  tags:
    - docker
  image: python:3.11
  services:
    - name: postgres:15
      alias: postgres
  variables:
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_DB: ppm_database
    POSTGRES_USER: login_ppm
    POSTGRES_PASSWORD: ***REMOVED-SEE-INCIDENT***
  before_script:
    - pip install psycopg2-binary
  script:
    - echo "Ждём postgres..."
    - sleep 5
    - python backend/scripts/connect-pg-test.py
  
