FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y postgresql-client curl wget unzip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=hashicorp/vault:1.15 /bin/vault /usr/local/bin/vault

WORKDIR /app

COPY requirements.txt requirements-ci.txt ./

RUN pip install --no-cache-dir -r requirements-ci.txt


