name: opscontrol-staging

services:
  postgres:
    image: postgres:16
    container_name: postgres-staging
    restart: always
    env_file:
      - .env.staging
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  vault-init:
    image: hashicorp/vault:1.15
    container_name: vault-init-staging
    user: "0:0"
    entrypoint: [ "sh", "-c", "chown -R 100:100 /vault/data" ]
    volumes:
      - vault_data:/vault/data
    restart: "no"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  vault:
    image: hashicorp/vault:1.15
    container_name: vault-staging
    restart: always
    depends_on:
      vault-init:
        condition: service_completed_successfully
    env_file:
      - .env.staging
    environment:
      TZ: Europe/Moscow
      VAULT_ADDR: http://127.0.0.1:8200
    privileged: "true" # Включить на астра линукс, временное решение
    volumes:
      - vault_data:/vault/data
      - ./vault-config:/vault/config
      - ./scripts/vault-init-dev.sh:/vault-init-dev.sh:ro
    ports:
      - "8222:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/config.hcl
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-staging
    restart: always
    depends_on:
      - postgres
      - vault
    volumes:
      - ../nginx/nginx-staging.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:80"
    networks:
      default:
        ipv4_address: 172.23.0.10
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  default:
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1

volumes:
  pg_data:
    external: true
    name: opscontrol-staging_pg_data
  vault_data:
    external: true
    name: opscontrol-staging_vault_data
