FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y postgresql-client curl wget unzip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN wget https://releases.hashicorp.com/vault/1.15.6/vault_1.15.6_linux_amd64.zip && \
    unzip vault_1.15.6_linux_amd64.zip && \
    mv vault /usr/local/bin/ && \
    rm vault_1.15.6_linux_amd64.zip

WORKDIR /app

COPY requirements.txt requirements-ci.txt ./

RUN pip install --no-cache-dir -r requirements-ci.txt


