services:
  postgres:
    image: postgres:16
    container_name: postgres-staging
    restart: always
    env_file:
      - .env.staging
    environment:
      TZ: Europe/Moscow
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"

  vault-init:
    image: hashicorp/vault:1.15
    container_name: vault-init-staging
    user: "0:0"
    entrypoint: [ "sh", "-c", "chown -R 100:100 /vault/data" ]
    volumes:
      - vault_data:/vault/data
    restart: "no"

  vault:
    image: hashicorp/vault:1.15
    container_name: vault-staging
    restart: always
    depends_on:
      vault-init:
        condition: service_completed_successfully
    env_file:
      - .env.staging
    environment:
      TZ: Europe/Moscow
      VAULT_ADDR: http://127.0.0.1:8200
    privileged: "true" # Включить на астра линукс, временное решение
    volumes:
      - vault_data:/vault/data
      - ./vault-config:/vault/config
      - ./scripts/vault-init.sh:/vault-init.sh:ro
    ports:
      - "8222:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/config.hcl

volumes:
  pg_data:
  vault_data:
