name: Backend CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker
        run: docker build -t ppm-backend ./backend

      - name: Run containers
        run: |
          docker network create test-net

          docker run -d \
            --name pg \
            --network test-net \
            -e POSTGRES_USER=ci \
            -e POSTGRES_PASSWORD=ci \
            -e POSTGRES_DB=ci_db \
            postgres:16

          sleep 5

          docker run -d \
            --name backend-test \
            --network test-net \
            -p 8000:8000 \
            -e DB_CREDS_MODE=static \
            -e POSTGRES_HOST=pg \
            -e POSTGRES_PORT=5432 \
            -e POSTGRES_DB=ci_db \
            -e POSTGRES_USER=ci \
            -e POSTGRES_PASSWORD=ci \
            ppm-backend

          sleep 5

          docker logs backend-test

      - name: Check API
        run: curl -f http://localhost:8000/api/status